root: true

env:
  es6: true
  shared-node-browser: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - prettier

globals:
  global: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2018

plugins:
  - import
  - prettier

rules:
  import/no-default-export: error
  import/order: error
  import/unambiguous: error
  no-restricted-syntax:
    - error
    - BindExpression
    - ClassProperty
    - Decorator
    - DoExpression
    - ExportDefaultSpecifier
    - ExportNamespaceSpecifier
    - TypeAnnotation
    - JSXElement
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5

settings:
  import/extensions: ['.mjs', '.js']
  import/resolver: babel-module

overrides:
  - files:
      - 'babel.config.js'
      - 'scripts/*.js'
    parser: espree
    parserOptions:
      sourceType: script
    plugins:
      - node
    rules:
      no-console: off
      node/no-unsupported-features: error
  - files:
      - 'demo/**/*.mjs'
      - 'demo/**/*.js'
    env:
      browser: true
  - files:
      - 'packages/*/test/**/*.mjs'
    env:
      mocha: true
    globals:
      assert: true
